# Generated by Django 4.2 on 2023-04-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='parent_id',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
