# Generated by Django 4.2 on 2023-04-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0002_ingredients_boolean_alter_ingredients_parent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='boolean',
            new_name='choosen',
        ),
    ]
