# Generated by Django 4.2 on 2023-04-19 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0003_rename_boolean_ingredients_choosen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='choosen',
            new_name='chosen',
        ),
    ]
