# Generated by Django 4.2 on 2023-05-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0009_ingredients_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='condition',
            field=models.CharField(choices=[('TVR', 'Твердое'), ('SHD', 'Жидкое'), ('NKZ', 'Не указано')], default='NKZ', max_length=3),
        ),
    ]
