# Generated by Django 4.2 on 2023-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0010_category_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='condition',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='condition',
            field=models.CharField(choices=[('TVR', 'Твердое'), ('SHD', 'Жидкое'), ('NKZ', 'Не указано')], default='NKZ', max_length=3),
        ),
    ]
