# Generated by Django 4.2 on 2023-05-13 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0011_remove_category_condition_ingredients_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='dop_pole',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='smallali.category'),
        ),
    ]
