# Generated by Django 4.2 on 2023-05-13 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0012_ingredients_dop_pole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='dop_pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='smallali.category'),
        ),
    ]
