# Generated by Django 4.2 on 2023-05-14 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0014_prodavec_ingredients_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='dop_pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingredientss', to='smallali.category'),
        ),
    ]
