# Generated by Django 4.2 on 2023-05-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smallali', '0017_sohranenia_alter_ingredients_dop_pole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='dop_pole',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='slug',
        ),
    ]
